//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTaskApp.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TestTaskDataBaseEntities : DbContext
    {
        public TestTaskDataBaseEntities()
            : base("name=TestTaskDataBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Manager> Manager { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<Sell> Sell { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
